---
listenAddressWebUI: localhost:1340  # Listen on all addresses available, port 1337
ListenAddressSingleHTTPFrontend: 0.0.0.0:1337 # Listen on all addresses available, port 1337
logLevel: "INFO"
actions:
  - title: Restart Plex
    icon: smile
    shell: docker restart plex

  # This will send 1 ping
  - title: Ping Google.com
    shell: ping google.com -c 1
