---
version: "2.1"
services:
  olivetin:
    image: nicholaswilde/olivetin:latest
    container_name: olivetin-default
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - app:/app
      - config:/config
      - defaults:/defaults
volumes:
  app:
  config:
  defaults:
